version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5176:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production
      - PORT=3006
      - FRONTEND_URL=http://localhost
    volumes:
      - audio-data:/app/output
      - db-data:/app/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  audio-data:
    driver: local
  db-data:
    driver: local
